{{/* GENERATED by `make manifests` (RBAC sync) -- DO NOT EDIT. Source: config/rbac/role.yaml */}}
{{- define "littlered.managerRules" -}}
- apiGroups:
  - ''
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.chuck-chuck-chuck.net
  resources:
  - littlereds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.chuck-chuck-chuck.net
  resources:
  - littlereds/finalizers
  verbs:
  - update
- apiGroups:
  - redis.chuck-chuck-chuck.net
  resources:
  - littlereds/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
