{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "littlered.fullname" . }}-metrics
  labels:
    {{- include "littlered.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "littlered.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
