{{- if .Values.podDisruptionBudget.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "littlered.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "littlered.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "littlered.selectorLabels" . | nindent 6 }}
{{- end }}
