{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "littlered.fullname" . }}
  labels:
    {{- include "littlered.labels" . | nindent 4 }}
    control-plane: controller-manager
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "littlered.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
{{- end }}
