apiVersion: v2
name: littlered-operator
description: A Helm chart for deploying the LittleRed Redis operator
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/tanne3/littlered-operator
sources:
  - https://github.com/tanne3/littlered-operator
maintainers:
  - name: tanne3
