apiVersion: v2
name: cluster-chaos
description: A Helm chart to deploy a LittleRed Redis Cluster and a chaos test client for manual investigation.
type: application
version: 0.1.0
appVersion: "1.0.0"
