version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /cmd/littlered
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /cmd/littlered-chaos-client
    schedule:
      interval: weekly

  - package-ecosystem: helm
    directory: /charts/littlered-operator
    schedule:
      interval: weekly
