# Get the git tag or short hash
GIT_TAG := $(shell if [ -n "$$(git describe --tags --exact-match 2>/dev/null)" ]; then \
                   git describe --tags --exact-match; \
               else \
                   git rev-parse --short HEAD; \
               fi)

LITTLERED_REGISTRY ?= ghcr.io/littlered-operator

IMAGES ?= littlered littlered-chaos-client

# Chaos Client image -- need to know for end-to-end testing
CHAOS_CLIENT_IMAGE ?= $(LITTLERED_REGISTRY)/littlered-chaos-client:$(GIT_TAG)

# Operator image
OPERATOR_IMAGE ?= $(LITTLERED_REGISTRY)/littlered:$(GIT_TAG)

# IMG is the canonical kubebuilder knob for the operator image. It defaults to
# OPERATOR_IMAGE; override it (e.g. `make docker-build docker-push deploy IMG=...`)
# to point the build/deploy at a different registry or tag.
IMG ?= $(OPERATOR_IMAGE)

# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker
HELM ?= helm
SKOPEO ?= skopeo

HELM_DIST ?= dist

# Helm requires strict semver for --version.
# Strip a leading 'v' from release tags (v0.1.0 → 0.1.0).
# Untagged commits (short hash) become 0.0.0-<hash> which is valid semver pre-release.
CHART_VERSION := $(shell v=$$(echo '$(GIT_TAG)' | sed 's/^v//'); \
                   printf '%s' "$$v" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+' \
                   && echo "$$v" || echo "0.0.0-$$v")

# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
SHELL = /usr/bin/env bash -o pipefail
.SHELLFLAGS = -ec

.PHONY: all
all: build

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk command is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: manifests
manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	"$(CONTROLLER_GEN)" rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
	@echo "Syncing CRDs to Helm chart..."
	@cp config/crd/bases/*.yaml charts/littlered/crds/ 2>/dev/null || true
	@echo "Syncing RBAC to Helm chart..."
	@python3 -c 'import yaml; role = yaml.safe_load(open("config/rbac/role.yaml")); rules_yaml = yaml.dump(role["rules"], indent=2, sort_keys=False); open("charts/littlered/templates/_managerrules.tpl", "w").write("{{/* GENERATED by `make manifests` (RBAC sync) -- DO NOT EDIT. Source: config/rbac/role.yaml */}}\n" + "{{- define \"littlered.managerRules\" -}}\n" + rules_yaml + "{{- end -}}\n")'

.PHONY: generate
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	"$(CONTROLLER_GEN)" object:headerFile="hack/boilerplate.go.txt" paths="./..."

.PHONY: fmt
fmt: ## Run go fmt against code.
	go fmt ./...

.PHONY: vet
vet: ## Run go vet against code.
	go vet ./...

.PHONY: test
test: manifests generate fmt vet setup-envtest ## Run tests.
	KUBEBUILDER_ASSETS="$(shell "$(ENVTEST)" use $(ENVTEST_K8S_VERSION) --bin-dir "$(LOCALBIN)" -p path)" go test $$(go list ./... | grep -v /e2e) -coverprofile cover.out

# TODO(user): To use a different vendor for e2e tests, modify the setup under 'tests/e2e'.
# The default setup assumes Kind is pre-installed and builds/loads the Manager Docker image locally.
# CertManager is installed by default; skip with:
# - CERT_MANAGER_INSTALL_SKIP=true
## Tool Binaries
KUBECTL ?= kubectl
KIND ?= kind

KIND_CLUSTER ?= littlered-test-e2e
SKIP_KIND_SETUP ?= false
SKIP_OPERATOR_DEPLOY ?= false

# Determine if the cluster already exists at parse-time (only if running e2e targets)
ifneq ($(filter test-e2e setup-test-e2e cleanup-test-e2e,$(MAKECMDGOALS)),)
# We use grep -xc to get an exact count of matching lines, stripping any noise.
CLUSTER_EXISTS := $(shell $(KIND) get clusters 2>/dev/null | grep -xc "$(KIND_CLUSTER)" | grep -q "^1$$" && echo true || echo false)
endif

.PHONY: setup-test-e2e
setup-test-e2e: ## Set up a Kind cluster for e2e tests if it does not exist
	@command -v $(KIND) >/dev/null 2>&1 || { \
		echo "Kind is not installed. Please install Kind manually."; \
		exit 1; \
	}
	@if [ "$(CLUSTER_EXISTS)" = "false" ]; then \
		echo "Creating Kind cluster '$(KIND_CLUSTER)'..."; \
		$(KIND) create cluster --name $(KIND_CLUSTER); \
	else \
		echo "Kind cluster '$(KIND_CLUSTER)' already exists. Skipping creation."; \
	fi

# E2E_SETUP_DEP defines the dependency for setting up the E2E environment.
# E2E_CLEANUP_DEP defines the dependency for cleaning up.
# We only cleanup if we are not skipping setup AND the cluster didn't exist before we started.
ifeq ($(SKIP_KIND_SETUP),true)
  E2E_SETUP_DEP =
  E2E_CLEANUP_DEP =
else
  E2E_SETUP_DEP = setup-test-e2e
  ifeq ($(CLUSTER_EXISTS),true)
    E2E_CLEANUP_DEP =
  else
    E2E_CLEANUP_DEP = cleanup-test-e2e
  endif
endif

E2E_VARS = KIND=$(KIND) KIND_CLUSTER=$(KIND_CLUSTER) SKIP_OPERATOR_DEPLOY=$(SKIP_OPERATOR_DEPLOY) SKIP_KIND_SETUP=$(SKIP_KIND_SETUP)

# FOCUS allows running specific tests by name.
# Example: make test-e2e FOCUS="Standalone"
ifneq ($(FOCUS),)
E2E_FOCUS = -ginkgo.focus='$(FOCUS)'
endif

# Ginkgo label selection (https://onsi.github.io/ginkgo/#spec-labels).
# Convention: heavy / opt-in tiers carry Label("extended"); everything else runs by
# default. This keeps a default run fast AND makes "run absolutely everything" a single
# switch — so opt-in tiers are covered by ONE knob instead of rotting behind scattered
# per-test flags.
#   make test-e2e                        # every tier except 'extended'
#   make test-e2e-all                    # every tier, including 'extended'
#   make test-e2e E2E_ALL=true           # same as test-e2e-all
#   make test-e2e LABEL_FILTER='reshard' # only the labelled tier(s)
E2E_LABEL_FILTER = !extended
ifeq ($(E2E_ALL),true)
E2E_LABEL_FILTER =
endif

# MODE cuts a run down to ONE deployment mode. A full run is ~50-85min, which is too
# long to be the only option when the work at hand is mode-specific ("we're looking at
# sentinel right now"). Every spec carries exactly one mode label -- see
# test/e2e/mode_labels_test.go for the scheme and hack/verify-e2e-mode-labels.sh for the
# partition check that keeps it honest.
#   make test-e2e MODE=sentinel          # sentinel only, still excluding 'extended'
#   make test-e2e MODE=cluster E2E_ALL=true
#   make list-e2e MODE=sentinel          # preview the selection, no cluster needed
# MODE composes with the extended rule (AND); an explicit LABEL_FILTER overrides both.
E2E_MODES = standalone sentinel cluster failover
ifneq ($(MODE),)
ifneq ($(filter-out $(E2E_MODES),$(MODE)),)
$(error MODE must be one of: $(E2E_MODES) (got '$(MODE)'))
endif
# `failover` keeps its pre-existing 'failover-mode' label rather than being renamed.
E2E_MODE_LABEL = $(MODE)
ifeq ($(MODE),failover)
E2E_MODE_LABEL = failover-mode
endif
ifeq ($(E2E_LABEL_FILTER),)
E2E_LABEL_FILTER := $(E2E_MODE_LABEL)
else
E2E_LABEL_FILTER := $(E2E_MODE_LABEL) && $(E2E_LABEL_FILTER)
endif
endif

ifneq ($(LABEL_FILTER),)
E2E_LABEL_FILTER = $(LABEL_FILTER)
endif
ifneq ($(E2E_LABEL_FILTER),)
E2E_LABELS = --ginkgo.label-filter='$(E2E_LABEL_FILTER)'
endif

# Suite deadline. Ginkgo v2's own --timeout defaults to 1h, and THAT is what interrupts a
# long full-matrix run (E2E_ALL=true) — go test's -timeout is only the outer watchdog and
# never got a say. Both now come from knobs, and the go one keeps a margin so Ginkgo
# interrupts and writes its report (cleanup nodes still run) instead of go panicking the
# process first.
#   make test-e2e E2E_ALL=true E2E_TIMEOUT=4h
E2E_TIMEOUT ?= 2h
E2E_GO_TIMEOUT ?= 3h

# DEBUG_ON_FAILURE=true ginkgo --fail-fast ./test/e2e/...
ifeq ($(DEBUG_ON_FAILURE),true)
FAIL_FAST = --ginkgo.fail-fast
E2E_VARS += DEBUG_ON_FAILURE=true
endif

# TEST_NAMESPACE allows overriding the namespace for e2e test resources (default: "littlered-e2e").
# Must not be "default". The namespace must not exist before the tests run (clean-slate requirement).
# Example: make test-e2e TEST_NAMESPACE=littlered-test
ifneq ($(TEST_NAMESPACE),)
E2E_VARS += TEST_NAMESPACE=$(TEST_NAMESPACE)
endif

# KUBECONTEXT_PINNING=true snapshots the current kubeconfig so that switching
# contexts in another terminal during a long run doesn't break tests.
# KUBECONTEXT=<name> pins to a specific context (implies pinning).
# Example: make test-e2e KUBECONTEXT_PINNING=true
# Example: make test-e2e KUBECONTEXT=kind-littlered-test-e2e
ifeq ($(KUBECONTEXT_PINNING),true)
E2E_VARS += KUBECONTEXT_PINNING=true
endif
ifneq ($(KUBECONTEXT),)
E2E_VARS += KUBECONTEXT=$(KUBECONTEXT)
endif
# Example: make test-e2e CLUSTER_SHARDS=5
# Example: make test-e2e CLUSTER_REPLICAS_PER_SHARD=2
ifneq ($(CLUSTER_SHARDS),)
E2E_VARS += CLUSTER_SHARDS=$(CLUSTER_SHARDS)
endif
ifneq ($(CLUSTER_REPLICAS_PER_SHARD),)
E2E_VARS += CLUSTER_REPLICAS_PER_SHARD=$(CLUSTER_REPLICAS_PER_SHARD)
endif

.PHONY: test-e2e
test-e2e: $(E2E_SETUP_DEP) run-test-e2e $(E2E_CLEANUP_DEP) ## Run the e2e tests (all tiers except 'extended').

.PHONY: test-e2e-all
test-e2e-all: ## Run ALL e2e tests, including 'extended'/opt-in tiers.
	$(MAKE) test-e2e E2E_ALL=true

.PHONY: run-test-e2e
run-test-e2e: manifests generate fmt vet
	$(E2E_VARS) OPERATOR_IMAGE=$(OPERATOR_IMAGE) CHAOS_CLIENT_IMAGE=$(CHAOS_CLIENT_IMAGE) go test -tags=e2e ./test/e2e/ -v -ginkgo.v -timeout $(E2E_GO_TIMEOUT) --ginkgo.timeout=$(E2E_TIMEOUT) $(FAIL_FAST) $(E2E_FOCUS) $(E2E_LABELS) $(ARGS)

# list-e2e previews the spec selection of an e2e run WITHOUT running anything. It reuses the
# same FOCUS/LABEL_FILTER/E2E_ALL knobs as test-e2e, so `make list-e2e <flags>` answers exactly
# "what would `make test-e2e <flags>` execute?" — the point is that the two cannot drift.
#   make list-e2e                             # the default tier set (everything but 'extended')
#   make list-e2e E2E_ALL=true                # every spec
#   make list-e2e LABEL_FILTER='failover-mode'
#   make list-e2e FOCUS='Standalone'
#   make list-e2e MODE=sentinel               # one deployment mode's specs
# --ginkgo.dry-run executes no nodes at all (not even BeforeSuite), so this needs no cluster and
# no kubecontext. Both -v flags are required: go's (or go test buffers the output away) and
# Ginkgo's (or the report is just dots). Deliberately has no codegen prerequisites — listing
# specs must never rewrite source.
.PHONY: list-e2e
list-e2e: ## List the specs an e2e run would select, without touching a cluster (honors FOCUS/LABEL_FILTER/E2E_ALL).
	@go test -tags=e2e ./test/e2e/ -v -timeout 5m --ginkgo.dry-run --ginkgo.v --ginkgo.no-color --ginkgo.seed=1 $(E2E_FOCUS) $(E2E_LABELS) 2>&1 | awk '/^Will run /{hdr=$$0} /^\/.*_test\.go:[0-9]+$$/{ if (prev !~ /^\[/ && prev != "") { loc=$$0; sub(/.*\/test\/e2e\//,"",loc); printf "%4d  %s\n        %s\n", ++n, prev, loc } } {prev=$$0} END{ if (n == 0) { print "no specs selected"; exit 1 } printf "\n%s (dry run -- nothing was executed)\n", hdr }'

.PHONY: verify-e2e-mode-labels
verify-e2e-mode-labels: ## Check the e2e mode labels partition the suite (no unlabelled/double-labelled specs).
	@./hack/verify-e2e-mode-labels.sh

.PHONY: cleanup-test-e2e
cleanup-test-e2e: ## Tear down the Kind cluster used for e2e tests
	@echo "Deleting Kind cluster '$(KIND_CLUSTER)'..."
	@$(KIND) delete cluster --name $(KIND_CLUSTER)

.PHONY: kind-load
kind-load: ## Load built images into the Kind cluster.
	@echo "Loading operator image into Kind cluster $(KIND_CLUSTER)..."
	$(CONTAINER_TOOL) save $(OPERATOR_IMAGE) | $(KIND) load image-archive /dev/stdin --name $(KIND_CLUSTER)
	@echo "Loading chaos client image into Kind cluster $(KIND_CLUSTER)..."
	$(CONTAINER_TOOL) save $(CHAOS_CLIENT_IMAGE) | $(KIND) load image-archive /dev/stdin --name $(KIND_CLUSTER)

.PHONY: lint
lint: golangci-lint ## Run golangci-lint linter
	"$(GOLANGCI_LINT)" run

.PHONY: lint-fix
lint-fix: golangci-lint ## Run golangci-lint linter and perform fixes
	"$(GOLANGCI_LINT)" run --fix

.PHONY: lint-config
lint-config: golangci-lint ## Verify golangci-lint linter configuration
	"$(GOLANGCI_LINT)" config verify

.PHONY: helm-lint
helm-lint: ## Lint the Helm chart and render it in every scoping mode.
	$(HELM) lint charts/littlered
	$(HELM) template littlered charts/littlered > /dev/null
	$(HELM) template littlered charts/littlered \
		--set 'scope.watchNamespaces={ns-a,ns-b}' > /dev/null
	$(HELM) template littlered charts/littlered \
		--set 'scope.ignoreNamespaces={kube-system}' > /dev/null
	$(HELM) template littlered charts/littlered \
		--set metrics.enabled=true \
		--set metrics.serviceMonitor.enabled=true \
		--set networkPolicy.enabled=true > /dev/null
	@echo "Helm chart lints and renders in all scoping modes."

##@ Build

.PHONY: build
build: manifests generate fmt vet lrctl ## Build manager and lrctl binaries.
	go build -o bin/manager cmd/littlered/main.go

.PHONY: lrctl
lrctl: manifests generate fmt vet ## Build lrctl binary.
	go build -o bin/lrctl cmd/lrctl/main.go

.PHONY: helm-package
helm-package: manifests ## Package the Helm chart into dist/ with the current version tag.
	mkdir -p $(HELM_DIST)
	$(HELM) package charts/littlered \
		--version $(CHART_VERSION) \
		--app-version $(GIT_TAG) \
		--destination $(HELM_DIST)

.PHONY: run
run: manifests generate fmt vet ## Run a controller from your host.
	go run ./cmd/littlered/main.go

.PHONY: docker-build
docker-build: ## Build the operator image (override registry/tag with IMG=).
	$(CONTAINER_TOOL) build -t $(IMG) -f cmd/littlered/Dockerfile .

.PHONY: docker-push
docker-push: ## Push the operator image (override with IMG=).
	$(CONTAINER_TOOL) push $(IMG)

# The project ships two images (operator + chaos client used by e2e). The
# `images`/`build-images`/`push-images` targets below build/push the whole set;
# the canonical `docker-build`/`docker-push` above cover just the operator image.
BUILD_TARGETS = $(addsuffix .build_image,$(IMAGES))
PUSH_TARGETS  = $(addsuffix .push_image,$(IMAGES))

.PHONY: $(BUILD_TARGETS) $(PUSH_TARGETS)

.PHONY: images
images: $(BUILD_TARGETS) $(PUSH_TARGETS)

.PHONY: build-images
build-images: $(BUILD_TARGETS)

.PHONY: push-images
push-images: $(PUSH_TARGETS)

# If you wish to build the manager image targeting other platforms you can use the --platform flag.
# (i.e. docker build --platform linux/arm64). However, you must enable docker buildKit for it.
# More info: https://docs.docker.com/develop/develop-images/build_enhancements/
$(BUILD_TARGETS): %.build_image:
	$(CONTAINER_TOOL) build -t $(LITTLERED_REGISTRY)/$*:$(GIT_TAG) -f cmd/$*/Dockerfile .

$(PUSH_TARGETS): %.push_image:
	$(CONTAINER_TOOL) push $(LITTLERED_REGISTRY)/$*:$(GIT_TAG)

# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
# architectures. (i.e. make docker-buildx IMG=myregistry/littlered:0.0.1). To use this option you need to:
# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
# - be able to push the image to your registry (i.e. if you do not set a valid value via OPERATOR_IMAGE=<myregistry/image:<tag>> then the export will fail)
# To adequately provide solutions that are compatible with multiple platforms, you should consider using this option.
PLATFORMS ?= linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
.PHONY: docker-buildx
docker-buildx: ## Build and push the operator image for cross-platform support (override with IMG=).
	# copy existing Dockerfile and insert --platform=${BUILDPLATFORM} into Dockerfile.cross, and preserve the original Dockerfile
	sed -e '1 s/\(^FROM\)/FROM --platform=\$$\{BUILDPLATFORM\}/; t' -e ' 1,// s//FROM --platform=\$$\{BUILDPLATFORM\}/' cmd/littlered/Dockerfile > Dockerfile.cross
	- $(CONTAINER_TOOL) buildx create --name littlered-builder
	$(CONTAINER_TOOL) buildx use littlered-builder
	- $(CONTAINER_TOOL) buildx build --push --platform=$(PLATFORMS) --tag $(IMG) -f Dockerfile.cross .
	- $(CONTAINER_TOOL) buildx rm littlered-builder
	rm Dockerfile.cross

##@ Deployment

ifndef ignore-not-found
  ignore-not-found = false
endif

# Helm only installs CRDs on initial install, not on upgrades.
# kubectl apply ensures CRDs are always up to date.
PULL_POLICY ?= Always

# Example: make deploy KUBECONTEXT=kind-littlered-test-e2e
KUBECTL_CTX_FLAGS :=
HELM_CTX_FLAGS :=
ifneq ($(KUBECONTEXT),)
KUBECTL_CTX_FLAGS := --context $(KUBECONTEXT)
HELM_CTX_FLAGS := --kube-context $(KUBECONTEXT)
endif

# Split IMG into repository and tag on the LAST ':' so registries with a port
# (host:5000/littlered:tag) are handled correctly. Fed to the Helm chart's
# image.repository / image.tag values by the deploy target.
IMG_REPOSITORY = $(shell printf '%s' '$(IMG)' | sed 's/:[^:/]*$$//')
IMG_TAG        = $(shell printf '%s' '$(IMG)' | sed 's/.*://')

.PHONY: install
install: manifests ## Install CRDs into the cluster.
	kubectl $(KUBECTL_CTX_FLAGS) apply -f charts/littlered/crds/

.PHONY: uninstall
uninstall: ## Uninstall CRDs from the cluster (use ignore-not-found=true to ignore missing).
	kubectl $(KUBECTL_CTX_FLAGS) delete -f charts/littlered/crds/ --ignore-not-found=$(ignore-not-found)

.PHONY: deploy
deploy: install ## Deploy the operator to the cluster via Helm (override image with IMG=).
	helm $(HELM_CTX_FLAGS) upgrade --install littlered ./charts/littlered \
		-n littlered-system --create-namespace \
		--set image.repository=$(IMG_REPOSITORY) \
		--set image.tag=$(IMG_TAG) \
		--set image.pullPolicy=$(PULL_POLICY)

.PHONY: undeploy
undeploy: ## Uninstall the operator's Helm release from the cluster.
	-helm $(HELM_CTX_FLAGS) uninstall -n littlered-system littlered 2>/dev/null

.PHONY: helm-push
helm-push: helm-package ## Push the Helm chart to the OCI registry (run 'helm registry login ghcr.io' first).
	$(HELM) push $(HELM_DIST)/littlered-$(CHART_VERSION).tgz oci://$(LITTLERED_REGISTRY)/charts

# IS_RELEASE_TAG is non-empty only when GIT_TAG is a proper semver release tag (vX.Y.Z or X.Y.Z).
IS_RELEASE_TAG := $(shell echo '$(GIT_TAG)' | grep -qE '^v?[0-9]+\.[0-9]+\.[0-9]+$$' && echo true)

.PHONY: push-latest
push-latest: ## Re-tag images as :latest (only runs on release tags, no-ops otherwise).
	@if [ -z "$(IS_RELEASE_TAG)" ]; then \
		echo "Skipping :latest — '$(GIT_TAG)' is not a release tag (vX.Y.Z)."; \
		exit 0; \
	fi; \
	echo "Pushing :latest for release $(GIT_TAG)..."; \
	$(foreach img,$(IMAGES), \
		$(CONTAINER_TOOL) tag $(LITTLERED_REGISTRY)/$(img):$(GIT_TAG) $(LITTLERED_REGISTRY)/$(img):latest && \
		$(CONTAINER_TOOL) push $(LITTLERED_REGISTRY)/$(img):latest && ) true
# NOTE: No :latest tag for the Helm chart. Helm treats the OCI tag / --version as a
# semver constraint, so a 'latest' tag is unusable (`helm pull --version latest` ->
# "improper constraint: latest"). Helm resolves the newest chart by picking the
# highest semver tag when --version is omitted, not by reading a 'latest' tag.

.PHONY: redeploy-all
redeploy-all: undeploy ## Full reset: uninstall helm chart, delete CRDs, and deploy fresh.
	-kubectl $(KUBECTL_CTX_FLAGS) delete crd littlereds.redis.chuck-chuck-chuck.net --ignore-not-found
	$(MAKE) deploy KUBECONTEXT=$(KUBECONTEXT)

.PHONY: pipeline
pipeline: images deploy install-lrctl

.PHONY: install-lrctl
install-lrctl: lrctl ## Install the lrctl binary to /usr/local/bin.
	sudo install -o root -g root -m 0755 bin/lrctl /usr/local/bin/lrctl

.PHONY: install-plugin
install-plugin: install-lrctl ## Install lrctl as a kubectl plugin (requires kubectl).
	@sudo ln -sf /usr/local/bin/lrctl /usr/local/bin/kubectl-lr
	@sudo ln -sf /usr/local/bin/lrctl /usr/local/bin/kubectl_complete-lr
	@echo "Plugin installed: you can now use 'kubectl lr ...' with shell completion."

##@ Dependencies

## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p "$(LOCALBIN)"

## Tool Binaries
CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen
ENVTEST ?= $(LOCALBIN)/setup-envtest
GOLANGCI_LINT = $(LOCALBIN)/golangci-lint
GO_LICENSES ?= $(LOCALBIN)/go-licenses

## Tool Versions
# Derived from the `tool` directives in go.mod so Dependabot's gomod ecosystem
# keeps them up to date. Override on the command line if you need a specific one.
CONTROLLER_TOOLS_VERSION ?= $(call gomodver,sigs.k8s.io/controller-tools)

#ENVTEST_VERSION is the version of controller-runtime release branch to fetch the envtest setup script (i.e. release-0.20)
ENVTEST_VERSION ?= $(shell v='$(call gomodver,sigs.k8s.io/controller-runtime)'; \
  [ -n "$$v" ] || { echo "Set ENVTEST_VERSION manually (controller-runtime replace has no tag)" >&2; exit 1; }; \
  printf '%s\n' "$$v" | sed -E 's/^v?([0-9]+)\.([0-9]+).*/release-\1.\2/')

#ENVTEST_K8S_VERSION is the version of Kubernetes to use for setting up ENVTEST binaries (i.e. 1.31)
ENVTEST_K8S_VERSION ?= $(shell v='$(call gomodver,k8s.io/api)'; \
  [ -n "$$v" ] || { echo "Set ENVTEST_K8S_VERSION manually (k8s.io/api replace has no tag)" >&2; exit 1; }; \
  printf '%s\n' "$$v" | sed -E 's/^v?[0-9]+\.([0-9]+).*/1.\1/')

GOLANGCI_LINT_VERSION ?= $(call gomodver,github.com/golangci/golangci-lint/v2)
GO_LICENSES_VERSION ?= $(call gomodver,github.com/google/go-licenses)

.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary.
$(CONTROLLER_GEN): $(LOCALBIN)
	$(call go-install-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen,$(CONTROLLER_TOOLS_VERSION))

.PHONY: setup-envtest
setup-envtest: envtest ## Download the binaries required for ENVTEST in the local bin directory.
	@echo "Setting up envtest binaries for Kubernetes version $(ENVTEST_K8S_VERSION)..."
	@"$(ENVTEST)" use $(ENVTEST_K8S_VERSION) --bin-dir "$(LOCALBIN)" -p path || { \
		echo "Error: Failed to set up envtest binaries for version $(ENVTEST_K8S_VERSION)."; \
		exit 1; \
	}

.PHONY: envtest
envtest: $(ENVTEST) ## Download setup-envtest locally if necessary.
$(ENVTEST): $(LOCALBIN)
	$(call go-install-tool,$(ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest,$(ENVTEST_VERSION))

.PHONY: golangci-lint
golangci-lint: $(GOLANGCI_LINT) ## Download golangci-lint locally if necessary.
$(GOLANGCI_LINT): $(LOCALBIN)
	$(call go-install-tool,$(GOLANGCI_LINT),github.com/golangci/golangci-lint/v2/cmd/golangci-lint,$(GOLANGCI_LINT_VERSION))

.PHONY: go-licenses
go-licenses: $(GO_LICENSES) ## Download go-licenses locally if necessary.
$(GO_LICENSES): $(LOCALBIN)
	$(call go-install-tool,$(GO_LICENSES),github.com/google/go-licenses,$(GO_LICENSES_VERSION))

# Main packages whose dependency graph is shipped (operator, chaos client, lrctl).
LICENSE_BINARIES ?= ./cmd/littlered ./cmd/littlered-chaos-client ./cmd/lrctl

.PHONY: licenses
licenses: go-licenses ## Regenerate THIRD_PARTY_LICENSES from the linked dependency graph.
	@echo "Generating THIRD_PARTY_LICENSES..."
	@$(GO_LICENSES) report $(LICENSE_BINARIES) --template hack/third-party-licenses.tpl > THIRD_PARTY_LICENSES.tmp \
		&& mv THIRD_PARTY_LICENSES.tmp THIRD_PARTY_LICENSES \
		|| { rm -f THIRD_PARTY_LICENSES.tmp; echo "go-licenses failed"; exit 1; }
	@echo "Wrote THIRD_PARTY_LICENSES ($$(grep -c '^Module:' THIRD_PARTY_LICENSES) modules)"

# go-install-tool will 'go install' any package with custom target and name of binary, if it doesn't exist
# $1 - target path with name of binary
# $2 - package url which can be installed
# $3 - specific version of package
define go-install-tool
@[ -f "$(1)-$(3)" ] && [ "$$(readlink -- "$(1)" 2>/dev/null)" = "$(1)-$(3)" ] || { \
set -e; \
package=$(2)@$(3) ;\
echo "Downloading $${package}" ;\
rm -f "$(1)" ;\
GOBIN="$(LOCALBIN)" go install $${package} ;\
mv "$(LOCALBIN)/$$(basename "$(1)")" "$(1)-$(3)" ;\
} ;\
ln -sf "$$(realpath "$(1)-$(3)")" "$(1)"
endef

define gomodver
$(shell go list -m -f '{{if .Replace}}{{.Replace.Version}}{{else}}{{.Version}}{{end}}' $(1) 2>/dev/null)
endef
