apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.cluster.name }}-chaos-client
  labels:
    app: chaos-client
    test: cluster-manual-investigation
spec:
  restartPolicy: Never
  initContainers:
  - name: wait-for-cluster
    image: valkey/valkey:8.0
    command: 
    - "sh"
    - "-c"
    - "until valkey-cli -h {{ .Values.cluster.name }} cluster info | grep 'cluster_state:ok'; do echo waiting for cluster to be ok; sleep 2; done;"
  containers:
  - name: chaos-client
    image: {{ .Values.chaosClient.image.repository }}:{{ .Values.chaosClient.image.tag }}
    imagePullPolicy: {{ .Values.chaosClient.image.pullPolicy }}
    args:
    - "-addrs={{ .Values.cluster.name }}:6379"
    - "-cluster"
    - "-prefix={{ .Values.chaosClient.keyPrefix }}"
    - "-duration={{ .Values.chaosClient.duration }}"
    - "-write-rate={{ .Values.chaosClient.writeRate }}"
    - "-timeout={{ .Values.chaosClient.timeout }}"
    - "-status-interval=5s"
