package cmd

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/littlered-operator/littlered-operator/internal/cli/discovery"
	"github.com/littlered-operator/littlered-operator/internal/cli/k8s"
	"github.com/littlered-operator/littlered-operator/internal/cli/types"
	redisclient "github.com/littlered-operator/littlered-operator/internal/redis"
	"github.com/spf13/cobra"
	"sigs.k8s.io/yaml"
)

var (
	importCRName string
)

var importCmd = &cobra.Command{
	Use:   "import <name>",
	Short: "Import a running Redis instance's configuration as a LittleRed custom resource",
	Long: `Connects to a running Redis instance, reads its live configuration via CONFIG GET,
and generates a LittleRed CR YAML that would deploy an equivalent instance.

Works with both LittleRed-managed and unmanaged instances (--unmanaged).`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		k8sClient, coreClient, config, defaultNS, err := k8s.NewClient(kubeconfig)
		if err != nil {
			return err
		}

		targetNS := namespace
		if targetNS == "" {
			targetNS = defaultNS
		}

		ctx := context.Background()

		cCtx, err := discovery.GetContext(ctx, k8sClient, targetNS, args[0], kind, unmanaged)
		if err != nil {
			return err
		}

		if len(cCtx.RedisPods) == 0 {
			return fmt.Errorf("no Redis pods found for %q", args[0])
		}

		// Pick a redis pod to query (prefer one that's running).
		pod := cCtx.RedisPods[0]
		for _, p := range cCtx.RedisPods {
			if p.Status.Phase == "Running" {
				pod = p
				break
			}
		}

		// -- Collect CONFIG GET * ------------------------------------------------
		configCmd := []string{"sh", "-c",
			`AUTH=""; [ -n "$REDIS_PASSWORD" ] && AUTH="-a $REDIS_PASSWORD --no-auth-warning"; redis-cli $AUTH CONFIG GET "*"`,
		}
		stdout, stderr, err := k8s.Exec(ctx, coreClient, config, cCtx.Namespace, pod.Name, cCtx.RedisContainer, configCmd)
		if err != nil {
			return fmt.Errorf("CONFIG GET failed on pod %s: %v (stderr: %s)", pod.Name, err, stderr)
		}
		redisConfig := parseAlternatingKV(stdout)

		// -- Collect INFO server --------------------------------------------------
		infoCmd := []string{"sh", "-c",
			`AUTH=""; [ -n "$REDIS_PASSWORD" ] && AUTH="-a $REDIS_PASSWORD --no-auth-warning"; redis-cli $AUTH INFO server`,
		}
		stdout, _, err = k8s.Exec(ctx, coreClient, config, cCtx.Namespace, pod.Name, cCtx.RedisContainer, infoCmd)
		if err != nil {
			// Non-fatal: we can still generate CR without version info.
			stdout = ""
		}
		serverInfo := parseInfoKV(stdout)

		// -- Infer mode -----------------------------------------------------------
		mode := inferMode(cCtx, serverInfo)

		// -- Cluster topology (if cluster mode) -----------------------------------
		var shards, replicasPerShard int
		if mode == modeCluster {
			nodesCmd := []string{"sh", "-c",
				`AUTH=""; [ -n "$REDIS_PASSWORD" ] && AUTH="-a $REDIS_PASSWORD --no-auth-warning"; redis-cli $AUTH CLUSTER NODES`,
			}
			stdout, _, err = k8s.Exec(ctx, coreClient, config, cCtx.Namespace, pod.Name, cCtx.RedisContainer, nodesCmd)
			if err == nil {
				shards, replicasPerShard = inferClusterTopology(redisclient.ParseClusterNodes(stdout))
			}
		}

		// -- Build the CR ---------------------------------------------------------
		crName := args[0]
		if importCRName != "" {
			crName = importCRName
		}

		// Extract the container image from the pod spec.
		containerImage := ""
		for _, c := range pod.Spec.Containers {
			if c.Name == cCtx.RedisContainer {
				containerImage = c.Image
				break
			}
		}

		cr := buildCR(crName, targetNS, mode, redisConfig, serverInfo, shards, replicasPerShard, containerImage)

		out, err := yaml.Marshal(cr)
		if err != nil {
			return fmt.Errorf("YAML marshal: %w", err)
		}

		// Print with header comment.
		fmt.Printf("# Generated by lrctl import from pod %s/%s at %s\n",
			cCtx.Namespace, pod.Name, time.Now().UTC().Format(time.RFC3339))
		fmt.Print(string(out))

		return nil
	},
}

func inferMode(cCtx *types.ClusterContext, serverInfo map[string]string) string {
	// INFO server contains redis_mode: standalone | sentinel | cluster.
	if m := serverInfo["redis_mode"]; m == modeCluster || m == modeSentinel || m == modeStandalone {
		return m
	}
	// Fall back to what the discovery module already knows (from the CR or --kind flag).
	if cCtx.Mode != "" {
		return cCtx.Mode
	}
	if len(cCtx.SentinelPods) > 0 {
		return modeSentinel
	}
	return modeStandalone
}

func inferClusterTopology(nodes []redisclient.ClusterNodeInfo) (shards, replicasPerShard int) {
	masters := 0
	replicas := 0
	for _, n := range nodes {
		for _, f := range n.Flags {
			if f == roleMaster {
				masters++
				break
			}
			if f == "slave" {
				replicas++
				break
			}
		}
	}
	if masters == 0 {
		return 3, 1 // fallback
	}
	shards = masters
	replicasPerShard = replicas / masters
	return
}

// buildCR constructs a minimal LittleRed CR as map[string]any with only non-default fields.
func buildCR(
	name, ns, mode string,
	config, serverInfo map[string]string,
	shards, replicasPerShard int,
	containerImage string,
) map[string]any {
	spec := map[string]any{
		"mode": mode,
	}

	// -- config section -------------------------------------------------------
	configSection := map[string]any{}

	if v := config["maxmemory"]; v != "" && v != "0" {
		if q := bytesToQuantity(v); q != "" {
			configSection["maxmemory"] = q
		}
	}
	if v := config["maxmemory-policy"]; v != "" && v != "noeviction" {
		configSection["maxmemoryPolicy"] = v
	}
	if v := atoiOr(config["timeout"], 0); v != 0 {
		configSection["timeout"] = v
	}
	if v := atoiOr(config["tcp-keepalive"], 300); v != 300 {
		configSection["tcpKeepalive"] = v
	}

	raw := buildRawConfig(config)
	if raw != "" {
		configSection["raw"] = raw
	}

	if len(configSection) > 0 {
		spec["config"] = configSection
	}

	// -- image ----------------------------------------------------------------
	spec["image"] = parseContainerImage(containerImage, serverInfo)

	// -- auth -----------------------------------------------------------------
	if v := config["requirepass"]; v != "" {
		spec["auth"] = map[string]any{
			"enabled":        true,
			"existingSecret": "", // TODO: create a Secret with a 'password' key and reference it here
		}
	}

	// -- tls ------------------------------------------------------------------
	if v := config["tls-port"]; v != "" && v != "0" {
		spec["tls"] = map[string]any{
			"enabled":        true,
			"existingSecret": "", // TODO: create a Secret with tls.crt and tls.key and reference it here
		}
	}

	// -- sentinel -------------------------------------------------------------
	if mode == modeSentinel {
		spec["sentinel"] = map[string]any{
			"quorum": 2,
		}
	}

	// -- cluster --------------------------------------------------------------
	if mode == modeCluster {
		clusterSection := map[string]any{}
		if shards > 0 {
			clusterSection["shards"] = shards
		}
		if replicasPerShard >= 0 {
			clusterSection["replicasPerShard"] = replicasPerShard
		}
		if v := atoiOr(config["cluster-node-timeout"], 15000); v != 15000 {
			clusterSection["clusterNodeTimeout"] = v
		}
		if len(clusterSection) > 0 {
			spec["cluster"] = clusterSection
		}
	}

	return map[string]any{
		"apiVersion": "redis.chuck-chuck-chuck.net/v1alpha1",
		"kind":       "LittleRed",
		"metadata": map[string]any{
			"name":      name,
			"namespace": ns,
		},
		"spec": spec,
	}
}

const defaultUpstreamPath = "library/redis"

// Known upstream image paths. If the running container uses one of these,
// the registry is a mirror and should be preserved. Anything else (bitnami, etc.)
// is a repackaged image and gets normalized to the upstream equivalent.
var upstreamPaths = map[string]bool{
	"redis":             true, // Docker Hub official shorthand
	"valkey/valkey":     true, // Valkey fork
	defaultUpstreamPath: true, // library/redis — Docker Hub canonical form
}

// parseContainerImage inspects the running container image and INFO server output
// to produce a normalized LittleRed ImageSpec.
//
// - Upstream images (redis, valkey/valkey): keep registry (it may be a mirror), use server version.
// - Non-upstream images (bitnami, etc.): replace with the upstream path, drop the
//
//	non-upstream registry, use the clean server version instead of the distro-specific tag.
func parseContainerImage(image string, serverInfo map[string]string) map[string]any {
	result := map[string]any{}

	// Determine upstream identity from INFO server.
	isValkey := serverInfo["valkey_version"] != ""
	serverVersion := serverInfo["valkey_version"]
	if serverVersion == "" {
		serverVersion = serverInfo["redis_version"]
	}

	upstreamPath := "library/redis"
	if isValkey {
		upstreamPath = defaultUpstreamPath
	}

	if image == "" {
		if upstreamPath != defaultUpstreamPath {
			result["path"] = upstreamPath
		}
		if serverVersion != "" {
			result["tag"] = serverVersion
		}
		return result
	}

	// Split image reference into registry, path, tag.
	registry, path, _ := splitImageRef(image)

	if upstreamPaths[path] {
		// Upstream image — keep custom registry (it's a mirror), drop docker.io (it's the default).
		if registry != "" && registry != "docker.io" {
			result["registry"] = registry
		}
	}
	// else: non-upstream (bitnami, etc.) — drop registry entirely.

	// Always set path to the upstream equivalent. Omit if it matches the LittleRed default.
	if upstreamPath != defaultUpstreamPath {
		result["path"] = upstreamPath
	}

	// Always prefer the clean server version over the container tag (e.g. "7.4.3" not "7.4.3-debian-12-r0").
	if serverVersion != "" {
		result["tag"] = serverVersion
	}

	return result
}

// splitImageRef splits a container image reference into registry, path, and tag.
// Examples:
//
//	"docker.io/bitnami/redis:7.4.3" → "docker.io", "bitnami/redis", "7.4.3"
//	"myregistry:5000/valkey/valkey:8.0" → "myregistry:5000", "valkey/valkey", "8.0"
//	"redis:7.4.3" → "", "redis", "7.4.3"
func splitImageRef(image string) (registry, path, tag string) {
	ref := image

	// Split tag.
	if i := strings.LastIndex(ref, ":"); i != -1 {
		afterColon := ref[i+1:]
		if !strings.Contains(afterColon, "/") {
			tag = afterColon
			ref = ref[:i]
		}
	}

	// Split registry from path. A first segment with a dot or colon is a registry hostname.
	path = ref
	if firstSegment, rest, ok := strings.Cut(ref, "/"); ok {
		if strings.Contains(firstSegment, ".") || strings.Contains(firstSegment, ":") {
			registry = firstSegment
			path = rest
		}
	}

	return
}

func init() {
	rootCmd.AddCommand(importCmd)
	importCmd.ValidArgsFunction = completeLittleRedNames
	importCmd.Flags().StringVar(&importCRName, "cr-name", "", "Override the metadata.name in the generated CR")
}
