/*
Copyright 2026 The littlered Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command rbacsync copies the `rules:` block of a controller-gen-generated
// ClusterRole into the Helm chart as a template helper.
//
// Why this exists: a Helm chart cannot reference files outside its own
// directory, so the RBAC rules the operator needs must be *copied* into
// charts/littlered/. That copy is checked in, and `make manifests` regenerates
// it; `make verify-generated` fails if it ever drifts from config/rbac/role.yaml.
//
// Why it is Go and not a YAML library round-trip: the output is checked in, so
// it must be byte-stable. Every Go YAML emitter in the module (all libyaml
// descendants) indents nested sequences and/or double-quotes scalars, which
// would rewrite the whole file. The rules block is a fixed, tiny shape —
// a sequence of mappings whose values are sequences of strings — so it is
// emitted directly here, in the layout controller-gen itself uses.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const header = "{{/* GENERATED by `make manifests` (RBAC sync) -- DO NOT EDIT. " +
	"Source: %s */}}\n"

const (
	defineOpen  = "{{- define \"littlered.managerRules\" -}}\n"
	defineClose = "{{- end -}}\n"
)

func main() {
	role := flag.String("role", "config/rbac/role.yaml", "path to the generated ClusterRole")
	out := flag.String("out", "charts/littlered/templates/_managerrules.tpl",
		"path of the Helm template helper to write")
	flag.Parse()

	src, err := os.ReadFile(*role)
	if err != nil {
		fail(err)
	}
	rendered, err := Render(src, *role)
	if err != nil {
		fail(fmt.Errorf("%s: %w", *role, err))
	}
	if err := os.WriteFile(*out, rendered, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "rbacsync: %v\n", err)
	os.Exit(1)
}

// Render turns a ClusterRole document into the Helm template helper that
// defines "littlered.managerRules". sourcePath only names the source in the
// generated-file header.
func Render(clusterRole []byte, sourcePath string) ([]byte, error) {
	var doc struct {
		Rules yaml.Node `yaml:"rules"`
	}
	if err := yaml.Unmarshal(clusterRole, &doc); err != nil {
		return nil, err
	}
	if doc.Rules.Kind != yaml.SequenceNode {
		return nil, fmt.Errorf("no `rules:` sequence found")
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, header, sourcePath)
	buf.WriteString(defineOpen)
	if err := writeRules(&buf, &doc.Rules); err != nil {
		return nil, err
	}
	buf.WriteString(defineClose)
	return buf.Bytes(), nil
}

// writeRules emits a sequence of mappings of string lists, preserving the
// source order of both the rules and the keys within each rule.
func writeRules(buf *bytes.Buffer, rules *yaml.Node) error {
	for _, rule := range rules.Content {
		if rule.Kind != yaml.MappingNode {
			return fmt.Errorf("rule is not a mapping (line %d)", rule.Line)
		}
		for i := 0; i < len(rule.Content); i += 2 {
			key, values := rule.Content[i], rule.Content[i+1]
			marker := "  "
			if i == 0 {
				marker = "- "
			}
			name, err := scalar(key)
			if err != nil {
				return err
			}
			fmt.Fprintf(buf, "%s%s:\n", marker, name)
			if values.Kind != yaml.SequenceNode {
				return fmt.Errorf("%s: value is not a sequence (line %d)", name, values.Line)
			}
			for _, v := range values.Content {
				item, err := scalar(v)
				if err != nil {
					return err
				}
				fmt.Fprintf(buf, "  - %s\n", item)
			}
		}
	}
	return nil
}

// plainSafe matches the strings that may be written as plain (unquoted) YAML
// scalars: the RBAC vocabulary of api groups, resources, verbs and
// non-resource URLs. Anything else — the empty api group, "*", anything with
// spaces or YAML indicators — is single-quoted below.
var plainSafe = regexp.MustCompile(`^[A-Za-z0-9/][A-Za-z0-9._/-]*$`)

// reserved are the plain scalars YAML 1.1 would read back as a bool or null
// rather than as a string.
var reserved = map[string]bool{
	"y": true, "n": true, "yes": true, "no": true, "true": true, "false": true,
	"on": true, "off": true, "null": true, "~": true,
}

func scalar(n *yaml.Node) (string, error) {
	if n.Kind != yaml.ScalarNode {
		return "", fmt.Errorf("expected a scalar (line %d)", n.Line)
	}
	if plainSafe.MatchString(n.Value) && !reserved[strings.ToLower(n.Value)] && !numeric(n.Value) {
		return n.Value, nil
	}
	return "'" + strings.ReplaceAll(n.Value, "'", "''") + "'", nil
}

func numeric(s string) bool {
	if _, err := strconv.ParseFloat(s, 64); err == nil {
		return true
	}
	_, err := strconv.ParseInt(s, 0, 64)
	return err == nil
}
