/*
Copyright 2026 The littlered Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestRenderLayout(t *testing.T) {
	// Key order is deliberately NOT alphabetical here: the emitter must
	// preserve the source order, not impose one.
	src := []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- verbs:
  - get
  apiGroups:
  - ""
  - apps
  resources:
  - pods
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - watch
`)
	want := "{{/* GENERATED by `make manifests` (RBAC sync) -- DO NOT EDIT. Source: r.yaml */}}\n" +
		"{{- define \"littlered.managerRules\" -}}\n" +
		"- verbs:\n" +
		"  - get\n" +
		"  apiGroups:\n" +
		"  - ''\n" +
		"  - apps\n" +
		"  resources:\n" +
		"  - pods\n" +
		"- apiGroups:\n" +
		"  - policy\n" +
		"  resources:\n" +
		"  - poddisruptionbudgets\n" +
		"  verbs:\n" +
		"  - watch\n" +
		"{{- end -}}\n"

	got, err := Render(src, "r.yaml")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if string(got) != want {
		t.Errorf("Render mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestRenderMatchesCheckedInChart is the drift guard: the chart helper is a
// checked-in copy of config/rbac/role.yaml, so `make test` must fail if the two
// disagree — not only `make verify-generated`.
func TestRenderMatchesCheckedInChart(t *testing.T) {
	const (
		roleRel  = "config/rbac/role.yaml"
		chartRel = "charts/littlered/templates/_managerrules.tpl"
	)
	root := filepath.Join("..", "..")
	src, err := os.ReadFile(filepath.Join(root, roleRel))
	if err != nil {
		t.Fatalf("read role: %v", err)
	}
	want, err := os.ReadFile(filepath.Join(root, chartRel))
	if err != nil {
		t.Fatalf("read chart helper: %v", err)
	}
	got, err := Render(src, roleRel)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if string(got) != string(want) {
		t.Errorf("%s is stale relative to %s — run `make manifests`", chartRel, roleRel)
	}
}

func TestScalarQuoting(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"apps", "apps"},
		{"redis.chuck-chuck-chuck.net", "redis.chuck-chuck-chuck.net"},
		{"littlereds/status", "littlereds/status"},
		{"/metrics", "/metrics"},
		{"", "''"},          // the core api group
		{"*", "'*'"},        // a YAML alias indicator
		{"yes", "'yes'"},    // would read back as a bool
		{"Off", "'Off'"},    // ditto, case-insensitively
		{"8080", "'8080'"},  // would read back as an int
		{"it's", "'it''s'"}, // apostrophes double
		{"two words", "'two words'"},
	}
	for _, c := range cases {
		var n yaml.Node
		n.Kind = yaml.ScalarNode
		n.Value = c.in
		got, err := scalar(&n)
		if err != nil {
			t.Errorf("scalar(%q): %v", c.in, err)
			continue
		}
		if got != c.want {
			t.Errorf("scalar(%q) = %s, want %s", c.in, got, c.want)
		}
	}
}

func TestRenderRejectsUnexpectedShapes(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want string
	}{
		{"no rules", "kind: ClusterRole\n", "no `rules:` sequence"},
		{"rules not a sequence", "rules: nope\n", "no `rules:` sequence"},
		{"rule not a mapping", "rules:\n- justastring\n", "not a mapping"},
		{"value not a sequence", "rules:\n- apiGroups: apps\n", "not a sequence"},
		{"nested value", "rules:\n- apiGroups:\n  - [a]\n", "expected a scalar"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, err := Render([]byte(c.src), "r.yaml")
			if err == nil {
				t.Fatalf("expected an error")
			}
			if !strings.Contains(err.Error(), c.want) {
				t.Errorf("error %q does not mention %q", err, c.want)
			}
		})
	}
}
