apiVersion: littlered.chuck-chuck-chuck.net/v1alpha1
kind: LittleRed
metadata:
  name: {{ .Values.sentinel.name }}
  annotations:
    littlered.chuck-chuck-chuck.net/disable-polling: {{ .Values.sentinel.disablePolling | quote }}
spec:
  mode: sentinel
  sentinel:
    quorum: {{ .Values.sentinel.quorum }}
    downAfterMilliseconds: {{ .Values.sentinel.downAfterMilliseconds }}
    failoverTimeout: {{ .Values.sentinel.failoverTimeout }}
